version: 2

models:
  # ============================================================================
  # Staging Models
  # ============================================================================
  - name: stg_customers
    description: >
      Staged customer data with standardized column names and basic cleaning.
      Source: raw_customers table from the source system.

    columns:
      - name: customer_id
        description: Unique identifier for each customer
        tests:
          - unique
          - not_null

      - name: customer_name
        description: Full name of the customer

      - name: email
        description: Customer email address
        tests:
          - unique

      - name: segment
        description: Customer segment classification (Enterprise, SMB, Consumer)
        tests:
          - accepted_values:
              values: ['Enterprise', 'SMB', 'Consumer']

      - name: created_at
        description: Timestamp when customer record was created
        tests:
          - not_null

  - name: stg_orders
    description: >
      Staged order data with cleaned fields and validated relationships.

    columns:
      - name: order_id
        description: Unique identifier for each order
        tests:
          - unique
          - not_null

      - name: customer_id
        description: Foreign key to customers
        tests:
          - not_null
          - relationships:
              to: ref('stg_customers')
              field: customer_id

      - name: order_date
        description: Date the order was placed
        tests:
          - not_null

      - name: total_amount
        description: Total order value in USD
        tests:
          - not_null

  # ============================================================================
  # Fact Models
  # ============================================================================
  - name: fct_orders
    description: >
      {{ cortex_describe_table('fct_orders') }}

    meta:
      owner: data-team
      contains_pii: false

    columns:
      - name: order_id
        description: "{{ cortex_describe_column('fct_orders', 'order_id') }}"
        tests:
          - unique
          - not_null

      - name: customer_id
        description: "{{ cortex_describe_column('fct_orders', 'customer_id') }}"
        tests:
          - not_null
          - relationships:
              to: ref('dim_customers')
              field: customer_id

      - name: order_date
        description: "{{ cortex_describe_column('fct_orders', 'order_date') }}"
        tests:
          - not_null

      - name: revenue
        description: Total revenue from the order
        tests:
          - not_null

  # ============================================================================
  # Dimension Models
  # ============================================================================
  - name: dim_customers
    description: >
      Customer dimension table with demographic and behavioral attributes.
      Updated daily with latest customer information.

    columns:
      - name: customer_id
        description: Surrogate key for customer dimension
        tests:
          - unique
          - not_null

      - name: customer_name
        description: Customer's full name

      - name: segment
        description: Customer segment for analysis and targeting

      - name: lifetime_value
        description: Calculated customer lifetime value in USD

      - name: first_order_date
        description: Date of customer's first order

      - name: last_order_date
        description: Date of customer's most recent order

  # ============================================================================
  # Mart Models
  # ============================================================================
  - name: mart_daily_sales
    description: >
      Daily sales aggregation for reporting and dashboards.
      Grain: one row per day per product category per region.

    meta:
      owner: analytics-team
      refresh_frequency: daily
      dashboard: Sales Overview

    columns:
      - name: date_day
        description: Calendar date
        tests:
          - not_null

      - name: product_category
        description: Product category name

      - name: region
        description: Sales region

      - name: total_revenue
        description: Sum of revenue for the day/category/region

      - name: order_count
        description: Number of orders

      - name: avg_order_value
        description: Average order value (revenue / orders)

# ============================================================================
# Sources
# ============================================================================
sources:
  - name: raw
    description: Raw data from source systems
    database: "{{ env_var('SNOWFLAKE_DATABASE') }}"
    schema: raw

    tables:
      - name: raw_customers
        description: Raw customer data from CRM
        loaded_at_field: _loaded_at
        freshness:
          warn_after: {count: 12, period: hour}
          error_after: {count: 24, period: hour}

      - name: raw_orders
        description: Raw order data from e-commerce platform
        loaded_at_field: _loaded_at
        freshness:
          warn_after: {count: 1, period: hour}
          error_after: {count: 6, period: hour}

      - name: raw_products
        description: Raw product catalog data
